#!/usr/bin/env python3
"""Render the deterministic human-readable delivery ledger report."""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any, Iterable


def _load_validator() -> Any:
    path = Path(__file__).with_name("validate-delivery-ledger.py")
    spec = importlib.util.spec_from_file_location("vibe_delivery_ledger_validator", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load ledger validator: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"cannot read {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise RuntimeError(f"expected a JSON object in {path}")
    return value


def _escape(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, list):
        value = ", ".join(str(item) for item in value) or "—"
    text = str(value).replace("|", "\\|").replace("\n", " ").strip()
    return text or "—"


def _evidence_summary(item: dict[str, Any]) -> str:
    production = item.get("productionEvidence")
    tests = item.get("testEvidence")
    receipts = item.get("verificationReceipts")
    return f"prod {len(production) if isinstance(production, list) else 0}; tests {len(tests) if isinstance(tests, list) else 0}; receipts {len(receipts) if isinstance(receipts, list) else 0}"


def _status_detail(item: dict[str, Any]) -> str:
    if item.get("status") == "waived" and isinstance(item.get("waiver"), dict):
        waiver = item["waiver"]
        return f"{waiver.get('reason', '')} ({waiver.get('userDecisionRef', '')})"
    if item.get("status") == "blocked-external" and isinstance(item.get("blocker"), dict):
        return str(item["blocker"].get("reason", ""))
    if item.get("applicability") == "not-applicable":
        return str(item.get("applicabilityReason", ""))
    return ""


def render_report(ledger: dict[str, Any], validation: Any) -> str:
    app_fingerprint = ledger.get("appSpec", {}).get("fingerprint", {})
    workspace_fingerprint = ledger.get("workspaceFingerprint", {})
    lines = [
        "# Requirement traceability",
        "",
        "> Generated from `.vibe/delivery-ledger.json`. Do not edit this file directly.",
        "",
        "## Verdicts",
        "",
        f"- implementation-complete: **{'YES' if validation.implementation_complete else 'NO'}**",
        f"- release-ready: **{'YES' if validation.release_ready else 'NO'}**",
        f"- closure audit current and PASS: **{'YES' if validation.audit_current_and_passed else 'NO'}**",
        "",
        "## Fingerprints",
        "",
        f"- AppSpec: `{_escape(app_fingerprint.get('digest'))}`",
        f"- Workspace: `{_escape(workspace_fingerprint.get('digest'))}`",
        f"- Git HEAD: `{_escape(workspace_fingerprint.get('gitHead'))}`",
        "",
        "## Acceptance scenarios",
        "",
        "| ID | Requirement | Flow | Required test surfaces | Status | Evidence | Detail |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    scenarios = ledger.get("acceptanceScenarios", [])
    if isinstance(scenarios, list):
        for item in sorted(
            (value for value in scenarios if isinstance(value, dict)),
            key=lambda value: str(value.get("id", "")),
        ):
            lines.append(
                "| "
                + " | ".join(
                    _escape(value)
                    for value in (
                        item.get("id"),
                        item.get("requirementId"),
                        item.get("flowId"),
                        item.get("requiredTestSurfaces"),
                        item.get("status"),
                        _evidence_summary(item),
                        _status_detail(item),
                    )
                )
                + " |"
            )
    lines.extend(
        [
            "",
            "## Quality gates",
            "",
            "| ID | Category | Platform | Requirement | Scope | Applicability | Status | Evidence | Detail |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    gates = ledger.get("qualityGates", [])
    if isinstance(gates, list):
        for item in sorted(
            (value for value in gates if isinstance(value, dict)),
            key=lambda value: str(value.get("id", "")),
        ):
            lines.append(
                "| "
                + " | ".join(
                    _escape(value)
                    for value in (
                        item.get("id"),
                        item.get("category"),
                        item.get("platform"),
                        item.get("requirement"),
                        item.get("readinessScope"),
                        item.get("applicability"),
                        item.get("status"),
                        _evidence_summary(item),
                        _status_detail(item),
                    )
                )
                + " |"
            )
    lines.extend(["", "## Validation", ""])
    if validation.errors:
        lines.append("### Errors")
        lines.append("")
        lines.extend(f"- {_escape(error)}" for error in sorted(validation.errors))
        lines.append("")
    if validation.warnings:
        lines.append("### Warnings")
        lines.append("")
        lines.extend(f"- {_escape(warning)}" for warning in sorted(validation.warnings))
        lines.append("")
    if not validation.errors and not validation.warnings:
        lines.extend(["No validation findings.", ""])
    return "\n".join(lines).rstrip() + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project_root", nargs="?", type=Path, default=Path.cwd())
    parser.add_argument("--ledger", type=Path, help="Ledger path")
    parser.add_argument("--output", type=Path, help="Generated Markdown path")
    parser.add_argument("--check", action="store_true", help="Fail if output differs; do not write")
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    project_root = args.project_root.resolve()
    ledger_path = (args.ledger or project_root / ".vibe" / "delivery-ledger.json").resolve()
    output = (
        args.output or project_root / "docs" / "requirement-traceability.generated.md"
    ).resolve()
    try:
        ledger = _read_json(ledger_path)
        validator = _load_validator()
        validation = validator.validate_ledger(project_root, ledger_path)
        rendered = render_report(ledger, validation)
    except (RuntimeError, OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    if args.check:
        if not output.is_file():
            print(f"ERROR: generated report is missing: {output}", file=sys.stderr)
            return 1
        if output.read_text(encoding="utf-8-sig") != rendered:
            print(f"ERROR: generated report is out of date: {output}", file=sys.stderr)
            return 1
        print(f"Generated report is current: {output}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Rendered delivery report: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
